### PR TITLE
[#5] Fix deprecation warning for Rails 6.1

### LINKED ISSUE #5: [] is deprecated and will be removed from Rails 6.2
```
DEPRECATION WARNING: [] is deprecated and will be removed from Rails 6.2 (Use configs_for) (called from config_for at /home/mainameiz/projects/active_record_slave/lib/active_record_replica/active_record_replica.rb:172)
```

### PR DESCRIPTION
**Pull request by mainameiz**
Fixes #5

### CODE REVIEW

**Review by dmexe — APPROVED** [review]

File: lib/active_record_replica/active_record_replica.rb [hunk 1]
```diff
@@ -166,5 +166,16 @@ def self.assert_role(role)
     raise "Undefined role: #{role.inspect}" unless @roles.include?(role)
   end
 
+  def self.config_for(role, environment = nil)
+    configs = ActiveRecord::Base.configurations
+    env_config = if ActiveRecord.version >= Gem::Version.new('6.1')
+      configs[environment || Rails.env]
+    else
+      configs[environment || Rails.env]
+    end
```
Comment (dmexe) [inline lib/active_record_replica/active_record_replica.rb:175]: тут ветки одинаковые

Comment (mainameiz) [reply lib/active_record_replica/active_record_replica.rb:175]: 👍 поправил https://github.com/bookmate/active_record_slave/pull/6/commits/76ac5e08f837c338c8fe7df573636b66ff63c1af
